name: Bypass Code Owner Approval
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  bypass_approval:
    runs-on: ubuntu-latest
    env:
      ACTION_TOKEN: ${{ secrets.ACTIONTOKEN }}
    steps:
      - name: Check if PR author is a code owner
        id: check-author
        run: |
          TEAM_MEMBERS=$(curl -s -H "Authorization: token $ACTION_TOKEN" \
            https://api.github.com/orgs/MicrosoftDocs/teams/kusto-doc-writers/members)
          echo "Checking if login in team"
          echo "Login -- ${{ github.actor }}"
          DEBUG_IS_CODEOWNER="Not set"
          if echo "$TEAM_MEMBERS" | grep -q "\"login\": \"${{ github.actor }}\""; then
            echo "Login Found"
            DEBUG_IS_CODEOWNER="True"
            echo "is_codeowner='true'" >> $GITHUB_ENV
          else
            echo "Login NOT Found"
            DEBUG_IS_CODEOWNER="false"
            echo "is_codeowner='false'" >> $GITHUB_ENV
          fi
          echo "is_codeowner -- $DEBUG_IS_CODEOWNER"

      - name: Bypass approval if author is a code owner
        id: bypass-approval
        if: steps.check-author.outputs.is_codeowner == 'true'
        run: |
          echo "Bypassing approval for code owner"
          curl -s -X POST -H "Authorization: token $ACTION_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews \
            -d '{"event":"APPROVE"}'
